name: Moves labeled issues to a specific project area

on:
  issues:
    types: [ labeled ]

jobs:
  move-ts-issues:
    if: ${{ github.event.label.name == 'TypeScript' }}
    uses: ./.github/workflows/add-label-move-to-area.yml
    with:
      field: 'Area'
      field_option: '🟦 Typescript'
      project_number: '1'
    secrets:
      token: ${{ secrets.ADD_TO_PROJECT_PAT }}
  move-test-issues:
    if: ${{ github.event.label.name == 'Testing' }}
    uses: ./.github/workflows/add-label-move-to-area.yml
    with:
      field: 'Area'
      field_option: '🚧 Testing'
      project_number: '1'
    secrets:
      token: ${{ secrets.ADD_TO_PROJECT_PAT }}
  empty-area-test:
    if: ${{ github.event.label.name == 'Empty' }}
    uses: ./.github/workflows/add-label-move-to-area.yml
    with:
      field: 'Area'
      field_option: ''
      project_number: '1'
    secrets:
      token: ${{ secrets.ADD_TO_PROJECT_PAT }}
  move-status-issue:
    if: ${{ github.event.label.name == 'Todo' }}
    uses: ./.github/workflows/add-label-move-to-area.yml
    with:
      field: 'Status'
      field_option: 'Todo'
      project_number: '1'
    secrets:
      token: ${{ secrets.ADD_TO_PROJECT_PAT }}
  move-dev-issue:
    if: ${{contains(github.event.label.name, format('role{0} dev', ':')) && !contains(github.event.label.name, format('role{0} design', ':'))}}
    uses: ./.github/workflows/add-label-move-to-area.yml
    with:
      field: 'Role'
      field_option: 'Dev'
      project_number: '1'
    secrets:
      token: ${{ secrets.ADD_TO_PROJECT_PAT }}
  move-design-issue:
    if: ${{contains(github.event.label.name, format('role{0} design', ':')) && !contains(github.event.label.name, format('role{0} dev', ':'))}}
    uses: ./.github/workflows/add-label-move-to-area.yml
    with:
      field: 'Role'
      field_option: 'Design'
      project_number: '1'
    secrets:
      token: ${{ secrets.ADD_TO_PROJECT_PAT }}
  move-cross-discipline-issue:
    if: ${{contains(github.event.label.name, format('role{0} design', ':')) && contains(github.event.label.name, format('role{0} dev', ':'))}}
    uses: ./.github/workflows/add-label-move-to-area.yml
    with:
      field: 'Role'
      field_option: 'Cross discipline'
      project_number: '1'
    secrets:
      token: ${{ secrets.ADD_TO_PROJECT_PAT }}
